// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateReviewInput struct {
	Rating  int    `json:"rating"`
	Comment string `json:"comment"`
	UserID  string `json:"userId"`
	ToolID  string `json:"toolId"`
}

type CreateToolInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
	Website     *string `json:"website,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
