// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"tools-review-backend/ent/review"
	"tools-review-backend/ent/schema"
	"tools-review-backend/ent/tool"
	"tools-review-backend/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescCreatedAt is the schema descriptor for created_at field.
	reviewDescCreatedAt := reviewFields[3].Descriptor()
	// review.DefaultCreatedAt holds the default value on creation for the created_at field.
	review.DefaultCreatedAt = reviewDescCreatedAt.Default.(func() time.Time)
	// reviewDescID is the schema descriptor for id field.
	reviewDescID := reviewFields[0].Descriptor()
	// review.DefaultID holds the default value on creation for the id field.
	review.DefaultID = reviewDescID.Default.(func() uuid.UUID)
	toolFields := schema.Tool{}.Fields()
	_ = toolFields
	// toolDescName is the schema descriptor for name field.
	toolDescName := toolFields[1].Descriptor()
	// tool.DefaultName holds the default value on creation for the name field.
	tool.DefaultName = toolDescName.Default.(string)
	// toolDescCreatedAt is the schema descriptor for created_at field.
	toolDescCreatedAt := toolFields[6].Descriptor()
	// tool.DefaultCreatedAt holds the default value on creation for the created_at field.
	tool.DefaultCreatedAt = toolDescCreatedAt.Default.(func() time.Time)
	// toolDescID is the schema descriptor for id field.
	toolDescID := toolFields[0].Descriptor()
	// tool.DefaultID holds the default value on creation for the id field.
	tool.DefaultID = toolDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
