// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
